# Default values for semaphore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica count
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
replicaCount: 1

# Container Image Parameters
# https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: semaphoreui/semaphore
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Pull an Image from a Private Registry
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
#  - name: MySecret

# String for overrides release name whose default is the semaphore.fullname
nameOverride: ""
fullnameOverride: ""

# Update strategy whose default is the RollingUpdate. 
# https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/
strategyUpdate:
  # Minimal replica count during the update
  maxSurge: 1
  # Maximum replica count unavailable during the update
  maxUnavailable: 1
  # Can be "Recreate" or "RollingUpdate"
  type: RollingUpdate

# Service Accounts
# https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "semaphore-sa"

# Custom pod annotations
# https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# Configure a Security Context for a Pod or Container
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true
  # runAsGroup: 1001
  # fsGroup: 1001

# Custom commands and arguments
containersSpec:
  command: [] # [ "sh", "-c", "sleep 3600" ]
  args: []

# Add extra environments variables from ConfigMap and Secret
extraEnv:
  - secretRef:
      name: semaphore-secret
  - configMapRef:
      name: semaphore-configmap

# Environment variables
env:
  - name: TZ
    value: Europe/Moscow

# Add extra molume mounts
extraVolumeMounts:
  - name: data
    mountPath: /semaphore

# Add extra volume
extraVolume:
  - name: data
    persistentVolumeClaim:
      # Persistent Volume Claim name whose default is the {{ .Chart.Name }}
      claimName: "semaphore-pvc"

# Ports and Protocols
# https://kubernetes.io/docs/reference/networking/ports-and-protocols/
ports:
  - name: http
    containerPort: 3000
    protocol: TCP

# Configure Liveness, Readiness and Startup Probes
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
probe:
  enabled: true

  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

  livenessProbe:
    failureThreshold: 5
    httpGet:
      port: http
      path: /
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
    initialDelaySeconds: 10

# Configure a Security Context for a Pod or Container
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Add extra init containers
# https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
extraInitContainers: []
  # - name: prepare
  #   image: busybox:1.34.1
  #   imagePullPolicy: "IfNotPresent"
  #   command:
  #     - sh
  #     - -c
  #     - |
  #       echo "Done"
  #   volumeMounts:
  #     - name: secrets-semaphore
  #       mountPath: "/mnt/secrets-semaphore"
  #       readOnly: true
  #     - name: config
  #       mountPath: "/mnt"
  #     - name: configmap-semaphore
  #       mountPath: "/mnt-template"

# Configuration service for semaphore
service:
  type: ClusterIP
  port: 3000
  annotations: {}

# Configuration ingress for semaphore
ingress:
  # On defaults ingress disabled
  enabled: false
  # Be sure to fill in if you use ingress
  className: ""
  annotations: {}
  hosts:
    - host: semaphore.local
      paths:
        - path: /
          pathType: Prefix

  # If use SSL connection
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Resource definition
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Horizontal Pod Autoscaling
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Persistent Volume Claim
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
persistentVolumeClaim:
  enabled: true
  name: semaphore-pvc
  storageClass: ""
  accessModes: 
    - ReadWriteOnce
  storage: 1Gi

# NodeSelector is the simplest recommended form of node selection constraint. 
# You can add the nodeSelector field to your Pod specification and specify the node labels you want the target node to have. 
# Kubernetes only schedules the Pod onto nodes that have each of the labels you specify.
# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
nodeSelector: {}

# Taints and Tolerations
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Custom ConfigMap
extraConfigMap:
# common
  # Public address of the Semaphore server. For example, 'https://company.com/semaphore'.
  webPath: ""
  # The port that the Semaphore server will listen on.
  appPort: 3000
  # The path to store temporary files
  tmpPath: /semaphore/tmp
  # Type of Git client. Can be 'cmd_git' or 'go_git'.
  gitClient: cmd_git
  # Max duration of a task in seconds.
  maxTaskDurationSec: 3600
  # Max number of parallel tasks that can be run on the server.
  maxParrallelTasks: 10
  # Deny password login.
  passwordLoginDisabled: False
  # Flag which enables remote runners.
  useRemoteRunner: False
  # Token which allows register new runners.
  runnerRegistrationToken: ""
  # Allow non-admin users to create projects.
  nonAdminCanCreateProject: True
  # Avoid host key checking by the tools Ansible uses to connect to the host.
  ansibleHostKeyChecking: True
# database settings
  # DB User
  dbUser: semaphore
  # DB Host
  dbHost: postgres.local
  # DB Port
  dbPort: 5432
  # DB Dialect (bolt/mysql/postgres)
  dbDialect: postgres
  # DB Name
  dbName: semaphore
# app
  loginAdmin: admin
  adminNickName: ADMIN
  adminEmail: admin@localhost
# email
  # Flag which enables email alerts.
  emailAlert: False
  # Email address of the sender.
  emailSender: semaphore@localhost
  # SMTP server hostname.
  emailHost: smtp.mail.ru
  # SMTP server port.
  emailPort: 25
  # Username for SMTP server authentication.
  emailUsername: semaphore
  # Use SSL or TLS for communication with the SMTP server.
  emailSecure: False
# LDAP
  ldapEnable: False
  ldapServer: ldap.example.com:636
  ldapNeedTls: True
  ldapBindDn: uid=ldap_user,cn=users,dc=example,dc=com
  ldapSearchDn: dc=example,dc=com
  ldapSearchFilter: (\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=example,dc=com))
  ldapNeedTls: True
# For use mapping LDAP
  ldapMappingDn: displayName
  ldapMappingMail: mail
  ldapMappingUid: sAMAccountName
  ldapMappingCn: cn
# Use Telegram Alerts
  telegramAlert: False
  telegramChat: "your_chat_id"
# custom secret
extraSecret:
  createSecret: True 
# security
  # If use extraSecret "false"
  dbPassword: password-for-db
  adminPassword: password-for-user-admin
  # Password for SMTP server authentication.
  emailPassword: password-for-email
  # Generate: cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32
  # LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 32 | xargs
  cookieHash: ""
  cookieEncryption: ""
  keyEncryption: ""
  ldapPassword: "password-for-ldap"
  telegramToken: "your_telegram_token"
