apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "semaphore.fullname" . }}
  namespace: {{ .Values.namespace | default .Chart.Name }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "semaphore.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategyUpdate.type | default "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategyUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.strategyUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "semaphore.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "semaphore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.containersSpec }}
          command: 
            {{- toYaml .Values.containersSpec.command | nindent 12 | default "[]" }}
          args: 
            {{- toYaml .Values.containersSpec.args | nindent 12 | default "[]" }}
          {{- end }}
          {{- if .Values.extraEnv }}
          envFrom:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          {{- if .Values.probe.enabled }}
          readinessProbe:
            {{- toYaml .Values.probe.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probe.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.extraVolume }}
      volumes:
        {{- toYaml .Values.extraVolume | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
