{{- if .Values.extraSecret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secret
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
stringData:
  SEMAPHORE_DB_PASS: '{{ .Values.extraSecret.dbPassword | default "semaphore" }}'
  SEMAPHORE_ADMIN_PASSWORD: '{{ .Values.extraSecret.adminPassword | default "adminPassword" }}'
{{- if .Values.extraConfigMap.emailAlert }}
  SEMAPHORE_EMAIL_PASSWORD: '{{ .Values.extraSecret.emailPassword | default "emailPassword" }}'
{{- end }}
{{- if .Values.extraConfigMap.telegramAlert }}
  SEMAPHORE_TELEGRAM_TOKEN: '{{ .Values.extraConfigMap.telegramToken | default "your_telegram_token" }}'
{{- end }}
  # Generate: cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32 | base64
  # LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 32 | xargs
  SEMAPHORE_COOKIE_HASH: '{{ .Values.extraSecret.cookieHash | default "AaIJvzJIY&+!Wm78e5_tzMviRUxr0a+P" }}'
  SEMAPHORE_COOKIE_ENCRYPTION: '{{ .Values.extraSecret.cookieEncryption | default "x9ITPj=e()!wgTvd%WqGJnP(%g=tGkR!" }}'
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: '{{ .Values.extraSecret.keyEncryption | default "5HrASV!ZG$Lo###sOSh8Zq3u_NiCJiGI" }}'
{{- if .Values.extraConfigMap.ldapEnable }}
  SEMAPHORE_LDAP_BIND_PASSWORD: '{{ .Values.extraSecret.ldapPassword | default "ldap_bind_account_password" }}'
{{- end }}
{{- end }}
