apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semaphore.fullname" . }}
  namespace: {{ .Values.namespace | default .Chart.Name }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
stringData:
  SEMAPHORE_DB_PASS: '{{ .Values.extraSecret.dbPassword | default "semaphore" }}'
  SEMAPHORE_ADMIN_PASSWORD: '{{ .Values.extraSecret.adminPassword | default "semaphore" }}'
  # Generate: cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32 | base64
  # LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 32 | xargs
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: '{{ .Values.extraSecret.keyEncryption | default "5HrASV!ZG$Lo###sOSh8Zq3u_NiCJiGI" }}'
{{- if .Values.extraConfigMap.ldapActivated }}
  SEMAPHORE_LDAP_PASSWORD: '{{ .Values.extraSecret.ldapPassword | default "ldap_bind_account_password" }}'
{{- end }}
