apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semaphore.fullname" . }}
  namespace: {{ .Values.namespace | default .Chart.Name }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
stringData:
  SEMAPHORE_DB_PASS: password
  SEMAPHORE_ADMIN_PASSWORD: password
  # Generate: cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32 | base64
  # LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 32 | xargs
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: 5HrASV!ZG$Lo###sOSh8Zq3u_NiCJiGI
  # SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'